// Generated by gencpp from file yolo_ros/BoxArray.msg
// DO NOT EDIT!


#ifndef YOLO_ROS_MESSAGE_BOXARRAY_H
#define YOLO_ROS_MESSAGE_BOXARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>

namespace yolo_ros
{
template <class ContainerAllocator>
struct BoxArray_
{
  typedef BoxArray_<ContainerAllocator> Type;

  BoxArray_()
    : data()  {
    }
  BoxArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::Float32MultiArray_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Float32MultiArray_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::yolo_ros::BoxArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_ros::BoxArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoxArray_

typedef ::yolo_ros::BoxArray_<std::allocator<void> > BoxArray;

typedef boost::shared_ptr< ::yolo_ros::BoxArray > BoxArrayPtr;
typedef boost::shared_ptr< ::yolo_ros::BoxArray const> BoxArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_ros::BoxArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_ros::BoxArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_ros::BoxArray_<ContainerAllocator1> & lhs, const ::yolo_ros::BoxArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_ros::BoxArray_<ContainerAllocator1> & lhs, const ::yolo_ros::BoxArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_ros::BoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_ros::BoxArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros::BoxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros::BoxArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros::BoxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros::BoxArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_ros::BoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8dd8c36b943fec9ff4f1f0860344475";
  }

  static const char* value(const ::yolo_ros::BoxArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8dd8c36b943fec9ULL;
  static const uint64_t static_value2 = 0xff4f1f0860344475ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_ros::BoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_ros/BoxArray";
  }

  static const char* value(const ::yolo_ros::BoxArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_ros::BoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray[] data\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::yolo_ros::BoxArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_ros::BoxArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoxArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_ros::BoxArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_ros::BoxArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_ROS_MESSAGE_BOXARRAY_H
